### ISSUE TITLE
Can't run examples

### ISSUE THREAD

**Issue by VirtualMaestro** [awayjs/awayjs-examples#6]
Hi guys,
I'm doing all 4 installation steps which are described on the main page, but npm throws errors (like ERROR in [at-loader]) and nothing works. (Also tried to set the newest Typescript version, but it doesn't work as well). Can you please check if installation process works for you ? Thank you

**Comment by 80prozent** [comment]
Hey
Thanks for reporting. Just tested myself, and i get errors with a new install too.
The dev branch works tho.
To get it to compile with the dev-branch, follow this steps:

- clear the current install (delete the `node_modules` folder)
- switch to dev-branch (`git checkout dev`)
- install again (`npm install`)
- `npm run start`

Hope this helps. 
We will look into fixing the master branch.

**Comment by VirtualMaestro** [comment]
Thank you, it works! I have two questions:
1. Is it possible to compile with the latest version of Typescript (2.6.2)? I couldn't do it.
2. When I tried to parse AWD format I got an error "Compressed AWD formats not yet supported".  I saw there is an implementation of this, but it is commented. Is it possible to uncomment and use it?

**Comment by 80prozent** [comment]
Hey
about your questions:
1. i have not tried 2.6.2 yet, but i am working on a project here that is compiling fine using typescript@2.6.1.
2. Compression is unfortunately not yet supported for AwayJS AWDParser. When we did the initial conversion to JS, our research showed us that the time the decompression takes was actually more than just loading a bit bigger / uncompressed AWD, so compression did never get a high priority for AwayJS-AWD. It has been a while, and its surly is worth looking into, but i dont see us having the time for it right now. We have been working on implementing a SWFParser into AwayJS which supports both lzma and zlip compression, so at some point in the future we will definitive add this to AWD too. In the meantime you should be able to uncompress your AWDs using AwayBuilder.

**Comment by VirtualMaestro** [comment]
Thank you for your answer!
